<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Oca' => $vendorDir . '/juanchorossi/oca-php-api/oca.php',
);
