<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitedb33208d122dc2c35a86a56e91a3d7a
{
    public static $classMap = array (
        'Oca' => __DIR__ . '/..' . '/juanchorossi/oca-php-api/oca.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInitedb33208d122dc2c35a86a56e91a3d7a::$classMap;

        }, null, ClassLoader::class);
    }
}
